dcmdr:
  children:
    apic:
      hosts:
        apic1-mlg1.cisco.com:
          ansible_host: 10.50.16.250
          aci_username: "ansible"
          aci_password: !vault |
            $ANSIBLE_VAULT;1.1;AES256
            38313261363831666336663662323530323435323832373231393466653337333464646637653765
            6562376664356536623134663538616664353835366437310a356132356638306636313665346534
            63333766366130396631656639376231336638343939323338313464356230626435353938343832
            6666396365636333660a663035333234623932373763326366343439336265663364376532376632
            3032
          aci_validate_certs: no
